# Generated by Django 4.0.5 on 2022-06-19 09:52

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0002_rename_tenant_unit_renter_remove_houseowner_address_and_more'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='HouseOwner',
            new_name='Owner',
        ),
        migrations.AlterModelOptions(
            name='owner',
            options={'ordering': ['-created_at'], 'verbose_name': 'Owner', 'verbose_name_plural': 'Owners'},
        ),
        migrations.AlterModelTable(
            name='owner',
            table='owner',
        ),
    ]
