# Generated by Django 4.0.5 on 2022-06-26 09:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0003_rename_houseowner_owner_alter_owner_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='address',
            field=models.CharField(max_length=255, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='bedrooms',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='description',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='rent',
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name='unit',
            name='square_feet',
            field=models.CharField(max_length=50, null=True),
        ),
        migrations.AddField(
            model_name='unit',
            name='status',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='unit',
            name='type',
            field=models.CharField(max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='owner',
            name='unit',
            field=models.ManyToManyField(blank=True, related_name='units', to='owner.unit'),
        ),
    ]
