# Generated by Django 4.0.5 on 2022-06-26 09:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0004_unit_address_unit_bedrooms_unit_description_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='address',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='square_feet',
            field=models.CharField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='type',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
