# Generated by Django 4.0.5 on 2022-06-27 04:07

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('owner', '0005_alter_unit_address_alter_unit_square_feet_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
    ]
