# Generated by Django 4.0.5 on 2022-06-27 11:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0008_alter_owner_user_alter_unit_renter'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='code',
            field=models.CharField(blank=True, max_length=9),
        ),
    ]
