# Generated by Django 4.0.5 on 2022-06-28 11:08

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_alter_renter_user'),
        ('owner', '0009_unit_code'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together=set(),
        ),
        migrations.AddField(
            model_name='unit',
            name='check_in_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='check_in_renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_in_renter', to='renter.renter'),
        ),
        migrations.AddField(
            model_name='unit',
            name='check_out_date',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
        migrations.AddField(
            model_name='unit',
            name='check_out_renter',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='check_out_renter', to='renter.renter'),
        ),
        migrations.RemoveField(
            model_name='unit',
            name='renter',
        ),
    ]
