# Generated by Django 4.0.5 on 2022-06-28 11:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0010_alter_unit_unique_together_unit_check_in_date_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='check_in_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='unit',
            name='check_out_date',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
