# Generated by Django 4.0.5 on 2022-06-29 06:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0002_alter_renter_user'),
        ('owner', '0011_alter_unit_check_in_date_alter_unit_check_out_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='remark',
            field=models.CharField(blank=True, max_length=255, null=True),
        ),
        migrations.AlterUniqueTogether(
            name='unit',
            unique_together={('check_in_renter', 'check_out_renter')},
        ),
    ]
