# Generated by Django 4.0.5 on 2022-06-30 06:35

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_unit_remark_unit_check_in_status_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='to_let_from',
            field=models.DateTimeField(default=django.utils.timezone.now),
        ),
    ]
