# Generated by Django 4.0.5 on 2022-06-30 06:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0014_unit_to_let_from'),
    ]

    operations = [
        migrations.AlterField(
            model_name='unit',
            name='to_let_from',
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
