# Generated by Django 4.0.5 on 2022-07-02 05:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0015_alter_unit_to_let_from'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='check_in_permission',
            field=models.IntegerField(null=True),
        ),
    ]
