# Generated by Django 4.0.5 on 2022-07-02 06:01

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0016_unit_check_in_permission'),
    ]

    operations = [
        migrations.RenameField(
            model_name='unit',
            old_name='check_in_permission',
            new_name='check_in_permission_nid',
        ),
    ]
