# Generated by Django 4.0.5 on 2022-07-03 06:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0018_alter_unit_check_in_permission_nid'),
    ]

    operations = [
        migrations.AddField(
            model_name='unit',
            name='phone',
            field=models.CharField(blank=True, max_length=14, null=True),
        ),
    ]
