# Generated by Django 4.0.5 on 2022-06-27 04:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0005_rename_familymembers_familymember_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='married_status',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.PROTECT, to='account.marriedstatus'),
        ),
    ]
