# Generated by Django 4.0.5 on 2022-06-27 05:24

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0006_alter_user_married_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='married_status',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='account.marriedstatus'),
        ),
    ]
