# Generated by Django 4.0.5 on 2022-07-02 09:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0007_alter_user_married_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.CharField(max_length=501, null=True),
        ),
    ]
