# Generated by Django 4.0.5 on 2022-07-02 10:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0008_alter_user_nid'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='nid',
            field=models.IntegerField(null=True),
        ),
    ]
