# Generated by Django 4.0.5 on 2022-07-17 10:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0010_remove_user_account_complete_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='nid_back_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
        migrations.AddField(
            model_name='user',
            name='nid_font_image',
            field=models.ImageField(blank=True, upload_to='images/'),
        ),
    ]
