# Generated by Django 4.0.5 on 2022-06-30 04:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('owner', '0013_remove_unit_remark_unit_check_in_status_and_more'),
        ('renter', '0002_alter_renter_user'),
    ]

    operations = [
        migrations.CreateModel(
            name='CheckInOut',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_by', models.CharField(max_length=255, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True, null=True)),
                ('created_from', models.CharField(max_length=255, null=True)),
                ('modified_by', models.CharField(max_length=255, null=True)),
                ('modified_at', models.DateTimeField(auto_now=True, null=True)),
                ('modified_from', models.CharField(max_length=255, null=True)),
                ('is_archived', models.BooleanField(default=False)),
                ('archived_by', models.CharField(max_length=255, null=True)),
                ('archived_at', models.DateTimeField(null=True)),
                ('archived_from', models.CharField(max_length=255, null=True)),
                ('check_in_date', models.DateTimeField(blank=True, null=True)),
                ('status', models.BooleanField(default=False)),
                ('remark', models.CharField(blank=True, max_length=255, null=True)),
                ('check_in_owner', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_owner', to='owner.owner')),
                ('check_in_unit', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='check_in_unit', to='owner.unit')),
                ('renter', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, to='renter.renter')),
            ],
            options={
                'verbose_name': 'Check In Out',
                'verbose_name_plural': 'Check In Outs',
                'db_table': 'checkinout',
                'ordering': ['-created_at'],
            },
        ),
    ]
