# Generated by Django 4.0.5 on 2022-07-01 07:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0004_rename_checkinout_checkin_alter_checkin_options_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='check_in_owner',
        ),
    ]
