# Generated by Django 4.0.5 on 2022-07-01 07:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0005_remove_checkin_check_in_owner'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='check_in_unit',
        ),
        migrations.AddField(
            model_name='checkin',
            name='unit_code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
