# Generated by Django 4.0.5 on 2022-07-01 07:35

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0006_remove_checkin_check_in_unit_checkin_unit_code'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='checkin',
            name='status',
        ),
    ]
