# Generated by Django 4.0.5 on 2022-07-02 04:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0007_remove_checkin_status'),
    ]

    operations = [
        migrations.AddField(
            model_name='checkin',
            name='status',
            field=models.BooleanField(default=True),
        ),
    ]
