# Generated by Django 4.0.5 on 2022-07-02 04:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('renter', '0008_checkin_status'),
    ]

    operations = [
        migrations.AlterField(
            model_name='checkin',
            name='status',
            field=models.BooleanField(default=False),
        ),
    ]
